name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - master   # change if your default branch is 'master'

permissions:
  contents: write   # needed to deploy to gh-pages branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16   # use Node 16 to avoid OpenSSL issues
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: |
          export NODE_OPTIONS=--openssl-legacy-provider
          npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
